PREFIX ex: <http://domus.usherbrooke.ca/ontologies/moredaha/2024/01/>

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?person
WHERE {
    ?person rdf:type ex:Person .
    ?person ex:isLocatedIn ex:livingroom1 .
    ex:tv1 ex:isLocatedIn ex:livingroom1 .
    ex:tv1 ex:hasState "Allumé" .
}

